{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf130
{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red28\green71\blue110;\red223\green223\blue223;\red52\green52\blue52;
\red7\green64\blue153;\red98\green0\blue117;\red19\green85\blue52;\red25\green0\blue135;\red28\green71\blue110;
\red223\green223\blue223;\red52\green52\blue52;\red7\green64\blue153;\red98\green0\blue117;\red19\green85\blue52;
\red25\green0\blue135;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardeftab720\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \
\pard\pardeftab720\sl260\partightenfactor0
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt 
\f1\fs22 \cf2 \cb3 \expnd0\expndtw0\kerning0
ALTER}}
\f1\fs22 \cf4 \cb3 \expnd0\expndtw0\kerning0
 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `DatosBasicosPacientes`\cf4  \cf6 DROP\cf4  \cf5 `TiposDocumento_idTiposDocumento`\cf4 ;\cf2 \
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt ALTER}}\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `DatosBasicosPacientes`\cf4  \cf6 CHANGE\cf4  \cf5 `idPaciente`\cf4  \cf5 `idPaciente`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/numeric-types.html"}}{\fldrslt \cf2 INT}}(\cf7 20\cf4 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_not"}}{\fldrslt \cf2 NOT}} \cf8 NULL\cf4  \cf6 AUTO_INCREMENT\cf4  \cf6 FIRST\cf4 ;\cf2 \
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt ALTER}}\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `DatosBasicosPacientes`\cf4  \cf6 ADD\cf4  \cf5 `documento`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf2 VARCHAR}}(\cf7 20\cf4 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_not"}}{\fldrslt \cf2 NOT}} \cf8 NULL\cf4  \cf6 AFTER\cf4  \cf5 `tipoDocumento`\cf4 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `DatosAdicionalesPacientes`\cf4  \cf6 CHANGE\cf4  \cf5 `idPaciente`\cf4  \cf5 `idPaciente`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/numeric-types.html"}}{\fldrslt \cf2 INT}}(\cf7 20\cf4 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_not"}}{\fldrslt \cf2 NOT}} \cf8 NULL\cf4  \cf6 AUTO_INCREMENT\cf4  \cf6 FIRST\cf4 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `DatosAdicionalesPacientes`\cf4  \cf6 ADD\cf4  \cf5 `documento`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf2 VARCHAR}}(\cf7 20\cf4 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_not"}}{\fldrslt \cf2 NOT}} \cf8 NULL\cf4  \cf6 AFTER\cf4  \cf5 `idPaciente`\cf4 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `HistoriaClinicaPreliminar`\cf4  \cf6 CHANGE\cf4  \cf5 `idhistoriaClinicaPreliminar`\cf4  \cf5 `idhistoriaClinicaPreliminar`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/numeric-types.html"}}{\fldrslt \cf2 INT}}(\cf7 11\cf4 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html#operator_not"}}{\fldrslt \cf2 NOT}} \cf8 NULL\cf4  \cf6 AUTO_INCREMENT\cf4 ;\
\
\pard\pardeftab720\sl260\partightenfactor0
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \cb3 ALTER}}\cf4 \cb3  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 TABLE}} \cf5 `HistoriaClinicaPreliminar`\cf4  \cf6 CHANGE\cf4  \cf5 `fecha`\cf4  \cf5 `fecha`\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/date-and-time-types.html"}}{\fldrslt \cf2 DATETIME}} \cf8 NULL\cf4  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf2 DEFAULT}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_current_timestamp"}}{\fldrslt \cf2 CURRENT_TIMESTAMP}};\
\
\pard\pardeftab720\sl260\partightenfactor0
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \cb10 \outl0\strokewidth0 \strokec9 ALTER}}\cf11 \cb10 \outl0\strokewidth0 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 TABLE}} \cf12 \strokec12 `HistoriaClinicaPreliminar`\cf11 \strokec11  \cf13 \strokec13 CHANGE\cf11 \strokec11  \cf12 \strokec12 `ojerasHiperpigmentadas`\cf11 \strokec11  \cf12 \strokec12 `ojerasHiperpigmentadas`\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf9 \strokec9 VARCHAR}}(\cf14 \strokec14 10\cf11 \strokec11 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 CHARACTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 SET}} utf8 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset-collations.html"}}{\fldrslt \cf9 \strokec9 COLLATE}} utf8_general_ci \cf15 \strokec15 NULL\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf9 \strokec9 DEFAULT}} \cf15 \strokec15 NULL\cf11 \strokec11 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 TABLE}} \cf12 \strokec12 `HistoriaClinicaPreliminar`\cf11 \strokec11  \cf13 \strokec13 CHANGE\cf11 \strokec11  \cf12 \strokec12 `surcoNasoyugalPronunciado`\cf11 \strokec11  \cf12 \strokec12 `surcoNasoyugalPronunciado`\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf9 \strokec9 VARCHAR}}(\cf14 \strokec14 10\cf11 \strokec11 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 CHARACTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 SET}} utf8 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset-collations.html"}}{\fldrslt \cf9 \strokec9 COLLATE}} utf8_general_ci \cf15 \strokec15 NULL\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf9 \strokec9 DEFAULT}} \cf15 \strokec15 NULL\cf11 \strokec11 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 TABLE}} \cf12 \strokec12 `HistoriaClinicaPreliminar`\cf11 \strokec11  \cf13 \strokec13 CHANGE\cf11 \strokec11  \cf12 \strokec12 `flacidezTarsal`\cf11 \strokec11  \cf12 \strokec12 `flacidezTarsal`\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf9 \strokec9 VARCHAR}}(\cf14 \strokec14 10\cf11 \strokec11 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 CHARACTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 SET}} utf8 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset-collations.html"}}{\fldrslt \cf9 \strokec9 COLLATE}} utf8_general_ci \cf15 \strokec15 NULL\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf9 \strokec9 DEFAULT}} \cf15 \strokec15 NULL\cf11 \strokec11 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 TABLE}} \cf12 \strokec12 `HistoriaClinicaPreliminar`\cf11 \strokec11  \cf13 \strokec13 CHANGE\cf11 \strokec11  \cf12 \strokec12 `secuelasAcneMotivoC`\cf11 \strokec11  \cf12 \strokec12 `secuelasAcneMotivoC`\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf9 \strokec9 VARCHAR}}(\cf14 \strokec14 10\cf11 \strokec11 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 CHARACTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 SET}} utf8 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset-collations.html"}}{\fldrslt \cf9 \strokec9 COLLATE}} utf8_general_ci \cf15 \strokec15 NULL\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf9 \strokec9 DEFAULT}} \cf15 \strokec15 NULL\cf11 \strokec11 ;\
\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 ALTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf9 \strokec9 TABLE}} \cf12 \strokec12 `HistoriaClinicaPreliminar`\cf11 \strokec11  \cf13 \strokec13 CHANGE\cf11 \strokec11  \cf12 \strokec12 `asimetriaFosasNasales_copy1`\cf11 \strokec11  \cf12 \strokec12 `asimetriaFosasNasalesR`\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/string-types.html"}}{\fldrslt \cf9 \strokec9 VARCHAR}}(\cf14 \strokec14 2\cf11 \strokec11 ) {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 CHARACTER}} {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset.html"}}{\fldrslt \cf9 \strokec9 SET}} utf8 {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/charset-collations.html"}}{\fldrslt \cf9 \strokec9 COLLATE}} utf8_general_ci \cf15 \strokec15 NULL\cf11 \strokec11  {\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=http://dev.mysql.com/doc/refman/5.5/en/miscellaneous-functions.html#function_default"}}{\fldrslt \cf9 \strokec9 DEFAULT}} \cf15 \strokec15 NULL\cf11 \strokec11 ;\
\
\cf4 \cb3 \outl0\strokewidth0 \
}